name: Build centipede-shields

on: [push, pull_request]

jobs:
  build:
    name: Build .NET assemblies
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build files
      run: dotnet publish src -c Release -o "output"
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: installer-artifacts
        path: output/CentiShields.dll
